## R-script to diagnose the downscaled (ESD) results based on the scores
## generated by the downscaling process.
## Rasmus Benestad

library(esd)

balls <- function(x,y=NULL) {
  for (i in 1:20) points(x,y,cex=seq(2,0.1,length=20)[i],
  col=rgb(i/20,i/20,i/20))
}

show <-  function(x,N,i,gcmnm.i,add=FALSE,xlim=NULL,ylim=NULL,verbose=FALSE,...) {
  n <- length(x$mean.diff)
  j <- 1:n
  col <- rgb(j/n,abs(sin(pi*j/n)),(1-j/n),0.3)
  if (is.null(xlim)) xlim <- c(-1,1)
  if (is.null(ylim)) ylim <- c(1,N)
  
  if (!add) {
    dev.new(width=7,height=10)
    par(bty="n")
    par0 <- par()
    plot(xlim,ylim,type="n",
         ylab="GCM",xlab=expression(1- sigma[p*r*e]/sigma[r*e*f]),
         main=paste("Diagnostics: common EOFs",attr(x,'variable')),
         xlim=xlim,ylim=ylim,col="grey")
    grid()
    #legend(xlim[1],ylim[2],c("same sign","different sign"),
    #       pch=c(19,21),bty="n",col="grey")
    par(xpd=TRUE)
    text(xlim[2],ylim[2],'EOF #',col='grey40',cex=0.8,pos=3)

    par(new=TRUE,fig=c(0.85,0.95,0.70,0.85),mar=c(0,3,0,0),
        cex.axis=0.7,yaxt="s",xaxt="n",las=1)
     colbar <- rbind(1:n,1:n)
    image(1:2,1:n,colbar,col=col)
    par(fig=par0$fig,mar=par0$mar,cex.axis=par0$cex.axis,
        yaxt=par0$yaxt,xaxt=par0$xaxt,las=par0$las,new=TRUE)
    plot(xlim,ylim,type="n",xlim=xlim,ylim=ylim,
         xlab='',ylab='',main='',sub='')
    par(par0$new)
  }
  cex <- abs(0.1 - x$mean.diff)/0.1
  pch <- rep(19,n); pch[cex < 0] <- 21
  cex <- abs(cex); cex[cex > 2] <- 2
  if (verbose) {
     print('Mean difference:');print(x$mean.diff)
     print('Ration of standard deviation');print(x$sd.ratio)
     print('Size');print(cex)
     print('col');print(col)
     #points(x$mean.diff,1-x$sd.ratio,pch=pch,col='grey75',cex=1)
  }
  
  points(1-x$sd.ratio,rep(i,n),pch=pch,col=col,cex=cex)
  text(xlim[1],i,gcmnm.i,pos=4,cex=0.7)
}

diagnoseESD <- function(fname='dse.aaca.t2m.rcp45.djf.rda',vn=NULL,is=NULL) {
  load(fname)
  if (is.null(vn)) Z <- eval(parse(text=substr(fname,1,nchar(fname)-8))) else
                   Z <- eval(parse(text=vn))
  
  dse.station <- as.station(Z,verbose=TRUE)

  lab <- substr(fname,nchar(fname)-12,nchar(fname)-4)
  s <- substr(lab,7,9)
  
  if (is.null(is)) is='svalbard'
  z <- subset(dse.station,is=is) 

  dev.new()
  plot(z,verbose=TRUE)
  figlab(loc(z))
  #dev.copy(png,paste(substr(fname,1,nchar(fname)-7),".s",is,".plot.png",sep=''))
  figlab(lab,ypos=0.975)
  dev.copy2pdf(file=paste(substr(fname,1,nchar(fname)-7),"s",s,".plot.pdf",sep=''))
  #dev.off()

  dev.new()
  vis(dse.station,colbar=list(breaks=seq(0,0.7,by=0.025),pal='warm'))
  #dev.copy(png,paste(substr(fname,1,nchar(fname)-7),"vis.png",sep=''))
  figlab(lab,ypos=0.975)
  figlab(varid(dse.station))
  dev.copy2pdf(file=paste(substr(fname,1,nchar(fname)-7),"s",s,"vis.pdf",sep=''))
  #dev.off()

  dev.new()
  diagnose(dse.station,verbose=TRUE)
  #dev.copy(png,paste(substr(fname,1,nchar(fname)-7),".diagnose.png",sep=''))
  figlab(lab,ypos=0.975)
  figlab(varid(dse.station))
  dev.copy2pdf(file=paste(substr(fname,1,nchar(fname)-7),"s",s,".diagnose.pdf",sep=''))
  #dev.off()

}

biasdiag <- function(y,predictor,it='djf',param='t2m',FUN='mean',FUNX='mean',
                      path="CMIP5.monthly/",pattern="tas_Amon_ens_",type='ncdf',
                     period=c(1950,2015),plot=FALSE,rcp='rcp45',verbose=TRUE,
                      lon=c(0,100),lat=c(65,90),select=NULL,xlim=NULL) {

  ## Diagnose the common EOFs and effect of bias-adjustment

  if (verbose) print(paste('biasdiag, it=',it))
  y <- subset(as.4seasons(y),it=it,verbose=verbose)

  if (verbose) print('predictor')
  if (is.character(predictor))
    t2m <- retrieve(ncfile=predictor,lon=lon,lat=lat,
                    type=type,verbose=verbose) else
  if (inherits(predictor,'field'))
    t2m <- subset(predictor,is=list(lon=lon,lat=lat))
  
  ## The reanalysis
  if (verbose) print('seasonal mean for predictor')
  T2M <- as.4seasons(t2m,FUN=FUNX)
  T2M <- subset(T2M,it=it,verbose=verbose)
  T2M <- matchdate(T2M,it=y)

  if (verbose) print(index(T2M))
    
  if (inherits(T2M,"eof")) T2M <- as.field(T2M)
  rm("predictor","t2m"); gc(reset=TRUE)

  # Ensemble GCMs
  path <- file.path(path,rcp,fsep = .Platform$file.sep)
  ncfiles <- list.files(path=path,pattern=pattern,full.name=TRUE)
  N <- length(ncfiles)

  if (is.null(select)) select <- 1:N else
                       N <- length(select)
  if (verbose) {print('GCMs:'); print(path); print(ncfiles[select])}

  d.y <- dim(y)
  years <- 1900:2100
  m <- length(years)
  months <- rep(month(y)[1],m)
  X <- matrix(rep(NA,N*m*d.y[2]),N,m*d.y[2])
  dim(X) <- c(d.y[2],N,m)
  gcmnm <- rep("",N)
  scorestats <- matrix(rep(NA,N*9),N,9)
  colnames(scorestats) <- c("1-r.xval","mean.diff","sd.ratio","autocorr.ratio",
                            "res.trend","res.K-S","res.ar1",'amplitude.ration',
                            "1-R2")

  t <- as.Date(paste(years,months,'01',sep='-'))

  cols <- rgb(seq(1,0,length=100),rep(0,100),seq(0,1,length=100),0.15)

  flog <- file("DSensemble.pca-log.txt","at")
  
  ## Set up a list environment to keep all the results
  results <- list(info='DSensemble.pca',pca=y) ## KMP 06-08-2015
  if (verbose) print("loop...") 
  for (i in 1:N) {
    if (verbose) print(ncfiles[select[i]])
    gcm <- retrieve(ncfile = ncfiles[select[i]],type=type,
                          lon=range(lon(T2M))+c(-2,2),
                          lat=range(lat(T2M))+c(-2,2),verbose=verbose)
    if (!is.null(it)) {
      if (verbose) print('Extract some months ot a time period')
      if (verbose) print(it)
      gcm <- subset(gcm,it=it)
    }
    #gcmnm[i] <- attr(gcm,'model_id')
    gcmnm.i <- paste(attr(gcm,'model_id'),attr(gcm,'realization'),sep="-r")
    gcmnm.i <- gsub(' ','',gcmnm.i)
    gcmnm.i <- gsub('-','.',gcmnm.i)
    print(gcmnm.i)
    if (inherits(T2M,'season')) {
      GCM <- as.4seasons(gcm,FUN=FUNX)
      GCM <- subset(GCM,it=season(T2M)[1])
    } else if (inherits(T2M,'annual')) {
      if (FUNX!='C.C.eq') GCM <- annual(gcm,FUN=FUNX,nmin=nmin) else
                          GCM <- annual(C.C.eq(gcm),FUN='mean',nmin=nmin)
    } else if (inherits(T2M,'month')) {
      if (length(table(month(y)))==1)
        GCM <- subset(gcm,it=month.abb[month(y)[1]]) else
        GCM <- gcm
    }
    T2MGCM <- combine(T2M,GCM)
    Z <- try(EOF(T2MGCM))
    diag <- diagnose(Z)
    if (plot) show(diag,N,i,gcmnm.i,add=(i!=1),xlim=xlim,verbose=verbose)
    eval(parse(text=paste('results$',it,'.',gcmnm.i,' <- diag',sep='')))
  }
  return(results)
}


scores <- function(fname='dse.aaca.t2m.rcp45.djf.rda',
                   vn=NULL,is=NULL,xlim=c(0,1),lab=NULL) {
  load(fname)
  if (is.null(lab)) lab <- substr(fname,nchar(fname)-12,nchar(fname)-4)
  if (is.null(vn)) vn <- substr(fname,1,nchar(fname)-8)
  Z <- eval(parse(text=vn))
  scores <- attr(Z,'scorestats')
  r <- 1 - scores[,1]
  R2 <- 1 - scores[,9]
  gcms <- names(Z)[-(1:2)]
  #print(gcms)
  n1 <- 3 + ceiling(log(1:length(gcms)+0.5)/log(10)) ;n2 <- nchar(gcms)
  gcms <- substr(gcms,n1,n2)
  #print(gcms)
  dev.new(width=6,height=10)
  par(bty='n')
  plot(r,(1:length(r)),xlim=xlim,
       xlab='Score',ylab='GCM')
  grid(ny=length(r))
  balls(r,(1:length(r)))
  cex <- 1.5
  col <- rgb(1,0,0,0.2)
  points(R2,(1:length(r)),pch=19,cex=cex,col=col)
  for (i in 1:length(r)) text(xlim[1],i,gcms[i],pos=4,cex=0.6,col='grey')
  figlab(lab,ypos=0.975)
  if (!is.expression(lab)) seas <- substr(lab,7,9) else
                           seas <- substr(fname,nchar(fname)-17,nchar(fname)-4)
  pdfname <- paste("paper59diagnose.",seas,".scores.pdf",sep='')
  dev.copy2pdf(file=pdfname)
}

#diagnoseESD('dse.aaca.t2m.rcp45.djf.rda')
#diagnoseESD('dse.aaca.t2m.rcp45.mam.rda')
#diagnoseESD('dse.aaca.t2m.rcp45.jja.rda')
#diagnoseESD('dse.aaca.t2m.rcp45.son.rda')
#diagnoseESD('dse.aaca.pr.rcp45.amjjas.wetmean.rda',vn='dse.aaca.pr.rcp45')
#diagnoseESD('dse.aaca.pr.rcp45.jfmond.wetmean.rda',vn='dse.aaca.pr.rcp45')
#diagnoseESD('dse.aaca.pr.rcp45.amjjas.wetfreq.rda',vn='dse.aaca.pr.rcp45')
#diagnoseESD('dse.aaca.pr.rcp45.jfmond.wetfreq.rda',vn='dse.aaca.pr.rcp45')

## Diagnose the bias-adjustments from common EOFs
#-----------------------------------------------------------------------
# Define season and parameter

#scores('dse.aaca.t2m.rcp45.djf.rda')
#scores('dse.aaca.t2m.rcp45.mam.rda')
#scores('dse.aaca.t2m.rcp45.jja.rda')
#scores('dse.aaca.t2m.rcp45.son.rda')
scores('dse.aaca.pr.rcp45.amjjas.wetmean.rda',
       vn='dse.aaca.pr.rcp45',xlim=c(-1,1),lab=expression(paste(mu,' (AMJJAS)')))
scores('dse.aaca.pr.rcp45.jfmond.wetmean.rda',
       vn='dse.aaca.pr.rcp45',xlim=c(-1,1),lab=expression(paste(mu,' (JFMOND)')))
scores('dse.aaca.pr.rcp45.amjjas.wetfreq.rda',
       vn='dse.aaca.pr.rcp45',xlim=c(-1,1),lab=expression(paste(f[w],' (AMJJAS)')))
scores('dse.aaca.pr.rcp45.jfmond.wetfreq.rda',
       vn='dse.aaca.pr.rcp45',xlim=c(-1,1),lab=expression(paste(f[w],' (JFMOND)')))

stop()

print('Compare common EOFs')
#param <- 't2m'
#FUN <- 'mean'
param <- 'pr'
FUN <- 'wet-freq'
#reanalysis <- 'air.mon.mean.nc'
reanalysis <- 'slp.mon.mean.nc'
#lon <- c(0,100); lat <- c(60,90)
lon <- c(-40,70); lat <- c(50,85)

if (param=='precip') FUNX <- 'C.C.eq' else FUNX <- 'mean'

## Get the predictand -> Y

if (exists('Y')) if (!inherits(Y,'station')) rm('Y')

if (!exists('Y')) {
  print('predictand')
  load(paste(param,'.aaca.rda',sep=''))
  Y <- eval(parse(text=paste(param,'.aaca',sep='')))
}

print('Get the GCMs')
#for (it in c('djf','mam','jja','son')) {
it <- month.abb[5:9]
#it <- month.abb[c(1:3,10:12)]

  ## Get the large-scale predictor:
  if (!exists('predictor')) {
    T2M <- retrieve(reanalysis,lon=lon,lat=lat)
    predictor <- subset(as.4seasons(T2M,FUNX=FUNX),it=it)
  } else if (length(month(subset(predictor,it=it)))==0)
    predictor <- subset(as.4seasons(T2M,FUNX=FUNX),it=it) 

  print(it)
#  diag <- biasdiag(Y,predictor,it,param,rcp='rcp45',FUN=FUN,FUNX=FUNX,plot=TRUE)
  diag.slp <- biasdiag(Y,predictor,it,param,rcp='rcp45',FUN=FUN,FUNX=FUNX,
                       pattern="psl_Amon_ens_",plot=TRUE,xlim=c(-2,1),lon=lon,lat=lat)
#  dev.copy2pdf(file=paste("diag.ceof.",it,".diagnose.pdf",sep=''))
  dev.copy2pdf(file=paste("diag.ceof.slp",it,".diagnose.pdf",sep=''))
#}
  
print('--- Completed diagnostics ---')

  
